config/routes.rb
Shelf::Application.routes.draw do
  devise_for :users
  resources :users, path: "profiles", :only => [:show, :edit, :update, :destroy]
  resources :books, :only => [:index, :show]
  resources :reviews, :only => [:new, :create, :update]

  devise_for :admins
  namespace :admin do
    resources :books
    resources :users
    resources :reviews
  end

  root to: 'books#index'
end

app/models/admin.rb
class Admin < User
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :isbn_number, :title
  validates_presence_of :title, :isbn_number
  validates_numericality_of :isbn_number
  validates_length_of :isbn_number, :is => 10
  validates_uniqueness_of :isbn_number
  has_many :reviews
  has_many :users, :through => :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  attr_accessible :rate, :book_attributes, :book_id, :user_id
  accepts_nested_attributes_for :book

  validates_numericality_of :rate
  validates_inclusion_of :rate, :in => 1..5

  validates_uniqueness_of :book_id, :scope => :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :avatar, :name, :email, :username, :password, :password_confirmation, :remember_me

  validates_presence_of :name, :username
  validates_uniqueness_of :username
  mount_uploader :avatar, AvatarUploader

  has_many :reviews
  has_many :books, :through => :reviews

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  inherit_resources

  def index
    @books = Book.paginate(:page => params[:page], :per_page => 20)
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < AdminController
  inherit_resources

  def index
    @reviews = Review.paginate(:page => params[:page], :per_page => 20)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  inherit_resources

  def index
    @users = User.paginate(:page => params[:page], :per_page => 20)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < InheritedResources::Base
  actions :index, :show

  def index
    @books = Book.paginate :page => params[:page], :per_page => 20
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base
  actions :new, :create, :update
  before_filter :authenticate_user!

  def new
    @review = current_user.reviews.build
    @book = @review.build_book
  end

  def create
    @review = current_user.reviews.build(params[:review])
    respond_to do |format|
      if @review.save
        format.html { redirect_to user_path(current_user), flash[:notice] => "Review successfully created!" }
        format.js { render :partial => 'update_rate', flash[:notice] => "Review successfully created!", :layout => false }
      else
        format.html { render 'new' }
        format.js { render :partial => 'update_rate', flash[:alert] => "Error adding this review", :layout => false }
      end
    end
  end

  def update
    @review = current_user.reviews.find(params[:id])
    @review.update_attributes(params[:review])
    respond_to do |format|
      format.js { render :partial => 'update_rate', flash[:notice] => "Review successfully created!", :layout => false }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  actions :show, :edit, :update, :destroy

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/books/_form.html.haml
= simple_form_for [:admin, @book], :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :isbn_number
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_books_path, :class => 'btn'

app/views/admin/books/edit.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/books/index.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:isbn_number)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @books.each do |book|
      %tr
        %td= link_to book.id
        %td= link_to book.title, admin_book_path(book)
        %td= book.isbn_number
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_book_path(book), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_book_path(book), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
= will_paginate @books
= link_to t('.new', :default => t("helpers.links.new")), new_admin_book_path, :class => 'btn btn-primary'

app/views/admin/books/new.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/books/show.html.haml
- model_class = Book
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @book.title
%p
  %strong= model_class.human_attribute_name(:isbn_number) + ':'
  %br
  = @book.isbn_number

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_books_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_book_path(@book), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_book_path(@book), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/admin/reviews/_form.html.haml
= simple_form_for [:admin, @review], :html => { :class => 'form-horizontal' } do |f|
  = f.input :rate
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_reviews_path, :class => 'btn'

app/views/admin/reviews/edit.html.haml
- model_class = Review
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/reviews/index.html.haml
- model_class = Review
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:user)
      %th= model_class.human_attribute_name(:rate)
      %th= model_class.human_attribute_name(:book)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @reviews.each do |review|
      %tr
        %td= link_to review.id, admin_review_path(review)
        %td= link_to review.user.name, admin_user_path(review.user)
        %td
          - review.rate.times do |value|
            %i{:class => "icon-star"}
        %td= link_to review.book.title, admin_book_path(review.book)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_review_path(review), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_review_path(review), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
= will_paginate @reviews
= link_to t('.new', :default => t("helpers.links.new")), new_admin_review_path, :class => 'btn btn-primary'

app/views/admin/reviews/new.html.haml
- model_class = Review
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/reviews/show.html.haml
- model_class = Review
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user) + ':'
  %br
  = @review.user.name
%p
  %strong= model_class.human_attribute_name(:book) + ':'
  %br
  = @review.book.title
%p
  %strong= model_class.human_attribute_name(:rate) + ':'
  %br
  - @review.rate.times do
    %i{:class => "icon-star"}

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_reviews_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_review_path(@review), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_review_path(@review), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :username
  = f.input :email
  = f.input :avatar
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:email)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, admin_user_path(user)
        %td= user.name
        %td= user.username
        %td= user.email
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
= will_paginate @users
= link_to t('.new', :default => t("helpers.links.new")), new_admin_user_path, :class => 'btn btn-primary'

app/views/admin/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/admin/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:avatar) + ':'
  %br
  = @user.avatar.url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/books/_review.html.haml
%tr{:id => "review-#{review.id}"}
  %td= link_to review.user.name, user_path(review.user)
  %td
    - review.rate.times do |star|
      %i{:class => "icon-star"}

app/views/books/_review_form.html.haml
#star-rating.pull-right
  - 5.times do |value|
    - marked = (value + 1 == review.try(:rate))
    = radio_button_tag 'review', 'rate', marked, :class => "rating", :value => (value + 1)

app/views/books/index.html.haml
.page-header
  %h1 Books
- @books.in_groups_of(4, false) do |group|
  %ul.thumbnails
    - group.each do |book|
      %li.span3
        .thumbnail
          %img{:data => {:src => "holder.js/160x160"}, :alt => ""}
          %p= link_to book.title, book_path(book)
          %small #{book.reviews.count} readers
= will_paginate @books

app/views/books/show.html.haml
.well
  - if user_signed_in?
    = render :partial => "review_form", :locals => {:review => @book.reviews.find_by_user_id(current_user.id)}
  .page-header
    %h1
      = @book.title
  %p
    %strong= 'ISBN Number'
    = @book.isbn_number
%legend Readers
%table.table.table-striped#readers-table
  %th Name
  %th Rate
  - @book.reviews.each do |review|
    %tr{:id => "review-#{review.id}"}
      %td= link_to review.user.name, user_path(review.user)
      %td
        - review.rate.times do |star|
          %i{:class => "icon-star"}

= content_for :custom_javascript do
  - unless user_signed_in? and current_user.books.include?(@book)
    :javascript
      jQuery(document).ready(function(){
        jQuery("#star-rating").rating(function(vote, event){
          book_id = "#{@book.id}";
          createReview(book_id, vote);
        })
      })
  - else
    :javascript
      jQuery(document).ready(function(){
        jQuery("#star-rating").rating(function(vote, event){
          review_id = "#{@book.reviews.find_by_user_id(current_user.id).id}";
          rateReview(review_id, vote);
        })
      });

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Shelf"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          = link_to 'Shelf', root_path, :class => 'brand'
          - if user_signed_in?
            = render :partial => "shared/logged_in_nav"
          - elsif admin_signed_in?
            = render :partial => "shared/admin_nav"
          - else
            = render :partial => "shared/default_nav"


    .container-fluid

      .row-fluid
        .span10.offset1
          #flash_messages
            = bootstrap_flash
          = yield

      %footer
        %p &copy; Tiago Paulino #{Date.today.year}
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield(:custom_javascript)

app/views/reviews/_update_rate.js.haml
jQuery("#flash_messages").html("#{escape_javascript(bootstrap_flash)}");
if (jQuery("#review-#{@review.id}").length > 0){
jQuery("#review-#{@review.id}").replaceWith("#{escape_javascript(render :partial => 'books/review', :locals => {:review => @review})}");
}else{
jQuery("#readers-table").append("#{escape_javascript(render :partial => 'books/review', :locals => {:review => @review})}");
jQuery("#star-rating").replaceWith("#{escape_javascript(render :partial => 'books/review_form', :locals => {:review => @review})}");
jQuery("#star-rating").rating(function(vote, event){
review_id = "#{@review.id}";
rateReview(review_id, vote);
});
}

app/views/reviews/new.html.haml
= simple_form_for @review, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification
  .span6
    %legend New Book
    %fieldset
      = f.simple_fields_for :book do |b|
        = b.input :title
        = b.input :isbn_number
      = f.label :rate
      .controls
        %label
          #rating
            - 5.times do |value|
              = radio_button_tag 'review[rate]', 'rate', false, :class => "rating", :value => (value + 1)
    .form-actions
      = f.button :submit, :class => 'btn-primary'

= content_for :custom_javascript do
  :javascript
      jQuery(document).ready(function(){
        jQuery("#rating").rating();
      })

app/views/shared/_admin_nav.html.haml
.container.nav-collapse.pull-left
  %ul.nav
    %li= link_to 'Users', admin_users_path
    %li= link_to "Books", admin_books_path
    %li= link_to "Reviews", admin_reviews_path
.container.nav-collapse.pull-right
  %ul.nav
    %li= link_to 'Logout', destroy_admin_session_path, :method => :delete

app/views/shared/_default_nav.haml
.btn-group.pull-right
    = link_to 'Sign up', new_user_registration_path, :class => "btn btn-primary"
    = link_to 'Sign in', new_user_session_path, :class => "btn"
    = link_to 'Sign in (Admin)', new_admin_session_path, :class => "btn"

app/views/shared/_logged_in_nav.html.haml
.nav.pull-left
  %li
    %a{:href => new_review_path } #{content_tag(:i, "", :class => "icon-plus")} Add Book
%ul.nav.pull-right
  %li
    = link_to current_user.name, user_path(current_user)
  %li
    = link_to 'Logout', destroy_user_session_path, :method => :delete

app/views/users/_books_list.html.haml
%legend #{@user.reviews.count} books
%table.table.table-striped
  %th Title
  %th Rate
  %tbody
    - @user.reviews.each do |review|
      %tr
        %td= link_to review.book.title, book_path(review.book)
        %td
          - review.rate.times do |star|
            %i{:class => "icon-star"}

app/views/users/edit.html.haml
= simple_form_for(current_user, :url => user_path(current_user), :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification
  %legend Edit Profile
  .form-inputs
    = f.input :name, :required => true, :autofocus => true
    = f.input :username, :required => true
    = f.input :email, :required => true
    = f.input :avatar, :as => :file

  .form-actions
    = f.button :submit, "Update"

app/views/users/show.html.haml
.well
  - if user_signed_in? and @user == current_user
    .pull-right
      = link_to 'Edit Profile', edit_user_path(@user)
  .row-fluid
    .span2
      = image_tag @user.avatar.url, :class => "img-polaroid", :alt => @user.username
    .span10
      %h1
        = @user.name
        - if @user.username.present?
          %small (#{@user.username})
      %p= @user.email
#books
  = render :partial => "books_list"